### ISSUE TITLE
this is really good interface.

### ISSUE THREAD

**Issue by gintering1000** [szermatt/visual-replace#1]
i agree this is last boss in replace package. 

- case toggle : great
- regex toggle : great
- word toggle : great
- highlight : great
- visual preview : great

but : input text ( it has bug like ctrlf : https://github.com/raxod502/ctrlf/issues/111 )

however~ i use vscode also. vscode user can go up and down from cursor after search. could i ask you new feature. 

- searcing globally ( it means when cursor is on center of file, all keyword on a file is highlighted )
- user can go up and down ( privous keyword / next keyword ) from cursor after write down [search text]

( for example, ctrlf searcher can go up and down with highlight )

i really want to find this function replacer like gui editor replacer

but every replacer is partically not good
- some package cant toggle case, word, regex interectively
- some package cant move keyword ( only replace all once )
- some package dont have highlight and preview like this

i hope this package be real boss like in vim world far in replacer

**Comment by gintering1000** [comment]
> i agree this is last boss in replace package. 
> 
> - case toggle : great
> - regex toggle : great
> - word toggle : great
> - highlight : great
> - visual preview : great
> 
> but : input text ( it has bug like ctrlf : https://github.com/raxod502/ctrlf/issues/111 )
> 
> however~ i use vscode also. vscode user can go up and down from cursor after search. could i ask you new feature. 
> 
> - searcing globally ( it means when cursor is on center of file, all keyword on a file is highlighted )
> - user can go up and down ( privous keyword / next keyword ) from cursor after write down [search text]
> 
> ( for example, ctrlf searcher can go up and down with highlight )
> 
> i really want to find this function replacer like gui editor replacer
> 
> but every replacer is partically not good
> - some package cant toggle case, word, regex interectively
> - some package cant move keyword ( only replace all once )
> - some package dont have highlight and preview like this
> 
> 
> i hope this package be real boss like in vim world far in replacer

**Comment by gintering1000** [comment]
user usecase process

user execute 'visual-regexp-interactive'
now user can toggle regex, wordlimit, upper/lowercase
user write down [searching keyword]
now user can move cursor up and down to highlighted keyword
user input tab or enter for go to replacing keyword input
now user can input [replacing keyword]
keyword is highlighted
user write down [replacing keyword]
before keyword is highlighted
replacing keyword is added to next searched keyword at editor
user can replace keyword
one keyword replace on cursor and cursor go to next keyword
one keyword replace on cursor and cursor go to privous keyword
all keyword changed and quit replace interactive status
undo one keyword changed
skip one keyword and go to next
skip one keyword and go to privous

**Comment by CyberShadow** [comment]
How does this package compare to https://github.com/benma/visual-regexp.el ?
Other than being newer and currently maintained.

**Comment by szermatt** [comment]
> but : input text ( it has bug like ctrlf : https://github.com/radian-software/ctrlf/issues/111 )

I can't reproduce this bug. The fact that another package had this bug make me suspect that it's an issue with Emacs, possible a bad interaction with input method. If you still have issues, please open another bug with detalis on Emacs version, OS and input method you use. 

>    searcing globally ( it means when cursor is on center of file, all keyword on a file is highlighted )
This works and can be made the default with visual-replace-default-to-full-scope

>    user can go up and down ( privous keyword / next keyword ) from cursor after write down [search text]

This works in the latest version

> How does this package compare to https://github.com/benma/visual-regexp.el ?

The big difference is that you edit the search string and the replacement at the same time.

**Comment by benma** [comment]
> The big difference is that you edit the search string and the replacement at the same time.

visual-regexp author here, I don't think that's true? You can edit both in the minibuffer side by side, which is supported by the native replace functions of Emacs. Or am I misunderstanding the feature you are talking about here?

![Image](https://github.com/user-attachments/assets/629fd904-1d72-4c90-aacb-e4c531ca5dbe)

**Comment by szermatt** [comment]
Maybe this is not phrased right.

What I was trying to point out is that UIs are different. With query-regexp, while you can edit both in the minibuffer side by side, as you've shown in the screenshot, normally you don't. It's a special case that not every one might be aware of. With visual-replace, you always do.
