### ISSUE TITLE
Using `local-set-key` to bind the trigger keypress to the secondary map

### ISSUE THREAD

**Issue by Stebalien** [szermatt/visual-replace#11]
For some context, I've bound `visual-replace-from-isearch` to `<tab>` to in `isearch-mode-map` so I can:

1. Enter `isearch`.
2. Begin my search.
3. Hit `<tab>` to switch to `visual-replace`.
4. Hit `<tab>` again to edit the search, etc.

This means I only need to bind a single key (one for isearch) instead of one for isearch and one for `visual-replace`. It also works around #8 because I can get an estimate of the number of matches before starting my replace session. But I also get all the advantages of `visual-replace`.

Unfortunately, the following bit of code is throwing a wrench in this flow:

https://github.com/szermatt/visual-replace/blob/dc349b9f197aa595d53ec86cbe834b7989d716a4/visual-replace.el#L622-L623

Because I activate `visual-replace` with `<tab>` (from `isearch`), `<tab>` gets re-bound to `visual-replace-secondary-mode-map` which kind of breaks everything.

IMO, the _correct_ way of binding `visual-replace-secondary-mode-map` to "whatever `visual-replace` is bound to" is:

```elisp
(define-key visual-replace-mode-map [remap visual-replace] visual-replace-secondary-mode-map)
```

But it appears that `visual-replace-global-mode-map` takes precedence. Or, at the very least, I just can't seem to get this to work.

**Comment by szermatt** [comment]
Thank for the bug report. Neat setup by the way! 

Calling `local-set-key` on the key that was used to trigger `visual-replace` was probably just a bad idea, but removing it would break backward compatibility.

Using `[remap visual-replace]` unfortunately doesn't work with the global mode map; there can be only one level of remap, and the global mode map just remaps query-replace. 

So all I can think of to fix this is to only remap if typing the trigger would invoke `visual-replace`. This works in the case where the global mode map is used, and this is really the main use case for this automatic binding. In all other cases, I think it'd be better to put the binding for the secondary mode map manually in `visual-mode-map'. 
This should fix your use-case. 

I'll send out a fix and probably update the doc to push for not relying on this automatic binding.

**Comment by Stebalien** [comment]
Thank you!  And thanks for the explanation of why it doesn't work.

Another option I considered was to use  `(where-is-internal 'visual-replace visual-replace-global-mode-map t)` to get the key binding, then bind that. But your way is likely less hacky.
