### ISSUE TITLE
Symbol’s value as variable is void: visual-replace-make-args

### ISSUE THREAD

**Issue by getong** [szermatt/visual-replace#13]
```
(use-package visual-replace
  :straight (visual-replace :type git :host github :repo "szermatt/visual-replace")
  :defer t
  :bind (("C-c r" . visual-replace)
         :map isearch-mode-map
         ("C-c r" . visual-replace-from-isearch)))
```
use with `visual-replace`, error msg:
```
Symbol’s value as variable is void: visual-replace-make-args
```

**Comment by szermatt** [comment]
This is very likely an issue with cl-lib missing when compiling, as visual-replace-make-args is created by cl-defstruct. 

The change above should fix it, but I haven't been able to reproduce the problem yet, so I'm not sure.

**Comment by szermatt** [comment]
Does the patch fix your issue?

I don't seem to be able to reproduce, even starting with an empty Emacs configuration. If the patch doesn't fix your issue, which version of Emacs and straight are you using?

**Comment by getong** [comment]
It works, thanks.
