### ISSUE TITLE
visual-replace-make-args nil and empty string from cause emacs to hang 

### ISSUE THREAD

**Issue by Inc0n** [szermatt/visual-replace#2]
The argument, `text` if it is either `nil` or "" (empty string) would cause the emacs to hang overall, in one occasion emacs was using over 46Gb of memory after I left it in such a condition for some hours. 

```
(visual-replace-read
  (visual-replace-make-args
	:from text
	:query t
	:word nil))
```

**Comment by szermatt** [comment]
Thank you for the bug report! Hanging emacs sounds pretty bad. 

I'd like to keep this issue open to look into that. 

Until then, a good workaround would be to bind `visual-replace-from-isearch` into `isearch-mode-map` to the same keybinding as `visual-replace`, for example:
```
 (use-package visual-replace
   :defer t
   :bind (("C-c l" . visual-replace)
          :map isearch-mode-map
          ("C-c l" . visual-replace-from-isearch)))
```

**Comment by szermatt** [comment]
This all seem to work without issue with the latest version, both in Emacs 26 and 29.
