### ISSUE TITLE
How to set initial value by selecting region

### ISSUE THREAD

**Issue by ghosty141** [szermatt/visual-replace#3]
Hi, I'm wondering how to set the initial value of visual-replace by selecting a word for example. I do a lot of refactoring where its quite neat to just select the thing I want to replace instead of having to come up with a regex for example.

**Comment by szermatt** [comment]
With the latest version, call `visual-replace-selected`. It'll fall back to the symbol at point.

**Comment by ghosty141** [comment]
> With the latest version, call `visual-replace-selected`. It'll fall back to using the symbol at point as thing to replace. 

Thank you for the work and quick reply! Much appreciated.
