### ISSUE TITLE
Set scope to default to 'full?

### ISSUE THREAD

**Issue by ghosty141** [szermatt/visual-replace#4]
Is there a way to set the scope to full by default? I've tried manually setting the visual-replace--scope variable but sadly that didn't help.

**Comment by szermatt** [comment]
There was no way… with the version I just pushed, you can just configure `visual-replace-default-to-full-scope` to `t` get the full scope unless the region is active (or to always get the full scope for visual-replace-selected or visual-replace-thing-at-point)

If you absoluely always want the full scope, set `visual-replace-initial-scope' to `'full` instead.

**Comment by szermatt** [comment]
closing again

**Comment by ghosty141** [comment]
> There was no way… with the version I just pushed, you can just configure `visual-replace-default-to-full-scope` to `t` get the full scope unless the region is active (or to always get the full scope for visual-replace-selected or visual-replace-thing-at-point)
> 
> 
> 
> If you absoluely always want the full scope, set `visual-replace-initial-scope' to `'full` instead. 

This sounds good, thank you!
