### ISSUE TITLE
Feature request: allow navigating matches like `isearch` and `query-replace` (and allow replacing an individual match like `query-replace`)

### ISSUE THREAD

**Issue by hab25** [szermatt/visual-replace#6]
Note that [`anzu-query-replace`](https://github.com/emacsorphanage/anzu/blob/5abb37455ea44fa401d5f4c1bdc58adb2448db67/anzu.el#L860) et. al. can also do this and, like `visual-replace`, also shows a visual preview (see gifs in the `anzu` `README.md`. However, that package is unmaintained with a lot of open and old bugs.

IMO having this feature is the final piece to Emacs having a current-buffer replace experience like in modern editors e.g. JetBrains IDEs and VSCode.

**Comment by szermatt** [comment]
Navigating matches is covered by the commit above. I'm moving the part about "allow replacing an individual match like query-replace" to https://github.com/szermatt/visual-replace/issues/7

**Comment by szermatt** [comment]
#7 is closed. See https://visual-replace.readthedocs.io/en/latest/usage.html#single-replacements for a quick description of the feature.
