### ISSUE TITLE
Count replacements

### ISSUE THREAD

**Issue by Stebalien** [szermatt/visual-replace#8]
Isearch has the ability to count replacements if `isearch-lazy-count` is set. If configured means the built-in `replace-regex` will display a count (before the prompt in the minibuffer) when matching.

It would be nice if `visual-replace` were able to do the same thing.

**Comment by szermatt** [comment]
Good idea. Yes, there could be an option for that.

**Comment by szermatt** [comment]
This is now available and can be enabled with `M-x customize-option visual-replace-display-total`
