### ISSUE TITLE
Return to previous position on tab

### ISSUE THREAD

**Issue by Stebalien** [szermatt/visual-replace#9]
(another feature request, sorry)

Right now, tabbing between the search string and the replacement drops the cursor at the beginning of the field. Usually I'd want it at the end (so I can work a bit on the search string, then work on the replacement, then extend the search string, etc.).

However, after trying that, I realized the most DWIM approach would be to have the cursor go back to where it was when I switched fields. For example:

| keys     | prompt        |
|-----------|----------------|
| `abc`     | `abc\|`         |
| `<tab>`   | `abc -> \|`     |
| `abd`     | `abc -> abd\|`  |
| `<tab>`   | `abc\| -> abd`  |
| `<left>b` | `abb\|c -> abd` |
| `<tab>`   | `abbc -> abd\|` |
| `<tab>`   | `abb\|c -> abd` |

**Comment by szermatt** [comment]
That sounds like a great idea, but I'd like to try it out and see how it works for a little while before submitting.

I've pushed the implementation to the branch tabpos. Give it a try as well and let me know what you think!

**Comment by Stebalien** [comment]
Thank you! It works perfectly except when transitioning from isearch to visual-replace (where it assumes the cursor starts at the beginning). There's no real fix for this because you don't know where the cursor was when searching, but IMO, starting the cursor at the end makes the most sense.

**Comment by szermatt** [comment]
Thinking about it, it seems that, when coming from isearch, it'd be more convenient to have the cursor at the beginning of the replacement, rather than the end of the match. This saves one TAB in most cases.

**Comment by Stebalien** [comment]
Ah, yes, I agree. I mean that if I tab back to the match I'd like the cursor to be at the end of the match.

**Comment by szermatt** [comment]
After having tried it for a while, I agree that it's definitely the best cursor behavior.
